import { Component, inject } from '@angular/core';
import { APP_THEME } from '../theme';

@Component({
  selector: 'app-cards',
  standalone: true,
  template: `
    <section>
      <h2 class="section-title">Cards</h2>
      <p class="section-desc">
        Cards compose effects (radius, shadow) + layout (padding), with optional colors and typography.
        Styled via CSS custom properties generated by the toolkit.
      </p>

      <div class="card-grid">
        <div [class]="getClass('cards', 'default')">
          <h3 class="card-title">Default Card</h3>
          <p class="card-body">Base radius and shadow from effects tokens.</p>
          <span [class]="getClass('badges', 'default')">default</span>
        </div>

        <div [class]="getClass('cards', 'elevated')">
          <h3 class="card-title">Elevated Card</h3>
          <p class="card-body">Larger radius and deeper shadow for emphasis.</p>
          <span [class]="getClass('badges', 'success')">live</span>
        </div>

        <div [class]="getClass('cards', 'hero')">
          <h3 style="margin: 0">Hero Card</h3>
          <p style="margin-top: 8px; opacity: 0.9">
            Full composition: colors + effects + layout + typography.
          </p>
        </div>
      </div>

      <h3 class="sub-title">CSS variables used</h3>
      <pre class="code">/* Default card uses: */
border-radius: var(--app-effects-radius);
box-shadow: var(--app-effects-shadow);
padding: var(--app-layout-spacing--xl);

/* Elevated variant: */
border-radius: var(--app-effects-radius--lg);
box-shadow: var(--app-effects-shadow--lg);</pre>
    </section>
  `,
  styles: [`
    .card-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 16px;
      margin-bottom: 24px;
    }
    .card-title {
      font-family: var(--app-typography-font-family--heading);
      font-size: var(--app-typography-font-size--xl);
      font-weight: var(--app-typography-font-weight--semibold);
      margin: 0;
    }
    .card-body {
      margin-top: 8px;
      color: #555;
      font-size: var(--app-typography-font-size);
      line-height: var(--app-typography-line-height);
    }
  `],
})
export class CardsComponent {
  private theme = inject(APP_THEME);

  getClass(group: "buttons" | "cards" | "badges", variant: string): string {
    return (this.theme.components.getClass as any)(group, variant) ?? '';
  }
}
